### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by melissamcewen** [illicitliliput/codecademy-project-3-the-scoop#1]
Hi I'm reviewing for codecademy. Great job on this! Everything works great and the automated tests pass. Your code is clear and well-written. I'm opening some "issues" with some feedback/tips/tricks I hope you find useful.

If you want to take it to the next level, I recommend the optional YAML exercise which is also good prep for structuring databases - a key skill for the final project.

Otherwise, hope you enjoyed working on this and are excited for the rest of the course because you're definitely ready for it! 👍

**Comment by illicitliliput** [comment]
Thanks a lot, it was fun to write :)
